#!/bin/bash
echo "🚀 Testing CardFi setup..."
echo "✅ Main dashboard: /dashboard"
echo "✅ Faucet page: /dashboard/faucet"
echo "✅ Updated sidebar with faucet link"
echo "✅ USDC balance shows faucet link when balance is 0"
echo ""
echo "📋 To test:"
echo "1. npm run dev"
echo "2. Visit http://localhost:3000/dashboard"
echo "3. Connect your wallet"
echo "4. If you have 0 USDC, you'll see a link to the faucet"
echo "5. Click 'Faucet' in the sidebar to visit /dashboard/faucet"
echo "6. Use the faucet page to get testnet USDC"
